# Generated by Django 4.2.10 on 2024-02-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, unique=True, verbose_name='Brand Name')),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('is_customer', models.BooleanField(default=True, verbose_name='Is Customer')),
                ('is_subcontractor', models.BooleanField(default=False, verbose_name='Is Sub Contractor')),
                ('is_managed_by_admin', models.BooleanField(default=False, verbose_name='Is Managed By Admin')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productype_name', models.CharField(max_length=255, verbose_name='Product Type Name')),
            ],
            options={
                'ordering': ['productype_name'],
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_name', models.CharField(max_length=255, verbose_name='SLA Name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq_id', models.CharField(max_length=100, unique=True, verbose_name='ENQ')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('is_dummy', models.BooleanField(default=False, verbose_name='Is Dummy')),
                ('project_start', models.DateField(verbose_name='Project-Start')),
                ('project_end', models.DateField(verbose_name='Project-End')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
            options={
                'ordering': ['enq_id'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Serial Number')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('customer_warranty_start', models.DateField(verbose_name='Customer Warranty Start')),
                ('customer_warranty_end', models.DateField(verbose_name='Customer Warranty End')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.model')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_type')),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sla')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
    ]
