# Generated by Django 4.2.10 on 2024-02-22 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_serviceteam_product_manager_datacenter_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project'),
        ),
    ]
