# Generated by Django 4.2.10 on 2024-03-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inventory_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_type', verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='productype_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sla',
            name='sla_name',
            field=models.CharField(max_length=255),
        ),
    ]
