# Generated by Django 4.2.10 on 2024-03-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_brand_brand_name_alter_inventory_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='datacenter',
            name='company',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='partner_company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='serviceteam',
            name='company',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='DataCenter',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
